services:
  envoy:
    image: envoyproxy/envoy:v1.31-latest
    ports:
      - 80:80
      # - 443:443
      # - 9901:9901
    volumes:
      - ./envoy-config-local.yaml:/etc/envoy/envoy.yaml
      - ./envoy_logs:/var/log
    environment:
      # this is done because there were some permission issues.
      # learn more here: https://www.envoyproxy.io/docs/envoy/latest/start/docker#start-docker
      - ENVOY_UID=0
    network_mode: host

  postgres:
      image: docker.io/postgres:16-bookworm
      restart: always
      environment:
        - POSTGRES_PASSWORD=admin
        - PGDATA=/var/lib/postgresql/data/pgdata
      ports:
        - 5432:5432
      volumes:
        - ./pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./backend/app/
      dockerfile: Dockerfile
    network_mode: host
    container_name: api-server

  tutorui:
    build:
      context: ./frontend/ui-app/
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    # ports:
    #   - "5000:5000"
    container_name: tutorui
    network_mode: host

